const now = new Date().toISOString();

export const parserFixtures = [
  {
    name: "clean multiline gold signal",
    rawMessage: {
      channel: "fixture-clean",
      messageId: 1,
      text: "BUY GOLD ENTRY 3345\nTP1 3350\nTP2 3360\nSL 3335",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 3345,
      targets: [3350, 3360],
      stopLoss: 3335,
      signalStatus: "ACTIVE",
      signalState: "ACTIVE",
      freshnessScore: "VERY_FRESH",
    },
  },
  {
    name: "emoji and symbol noisy partial",
    rawMessage: {
      channel: "fixture-noisy",
      messageId: 2,
      text: "🚀🚀 BUY GOLD NOW 🔥🔥",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "unordered fields",
    rawMessage: {
      channel: "fixture-unordered",
      messageId: 3,
      text: "TP1 1.0920\nSL 1.0840\nEUR/USD buy @ 1.0880\nTP2 1.0960",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.088,
      targets: [1.092, 1.096],
      stopLoss: 1.084,
    },
  },
  {
    name: "dynamic crypto quoted pair",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 15,
      text: "BUY SOLUSDT @ 142.50\nTP1 146\nSL 139",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "SOLUSD",
      action: "BUY",
      entry: 142.5,
      targets: [146],
      stopLoss: 139,
    },
  },
  {
    name: "dynamic index pair",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 16,
      text: "GER40 SELL 18850\nTP 18790\nSL 18910",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GER40",
      action: "SELL",
      entry: 18850,
      targets: [18790],
      stopLoss: 18910,
    },
  },
  {
    name: "silver alias normalizes to xagusd",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 17,
      text: "SILVER BUY @ 31.25\nTP1 31.80\nSL 30.90",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAGUSD",
      action: "BUY",
      entry: 31.25,
      targets: [31.8],
      stopLoss: 30.9,
    },
  },
  {
    name: "update breakeven",
    rawMessage: {
      channel: "fixture-update",
      messageId: 4,
      text: "Move SL to breakeven",
      timestamp: now,
    },
    expected: {
      classification: "UPDATE_SIGNAL",
      managementAction: "MOVE_SL_BREAKEVEN",
      signalStatus: "ACTIVE",
      signalState: "ACTIVE",
    },
  },
  {
    name: "result target hit",
    rawMessage: {
      channel: "fixture-result",
      messageId: 5,
      text: "TP1 HIT ✅",
      timestamp: now,
    },
    expected: {
      classification: "RESULT_SIGNAL",
      resultActionType: "TARGET_HIT",
      signalStatus: "PARTIAL",
      signalState: "PARTIAL",
    },
  },
  {
    name: "promo spam",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 6,
      text: "Join VIP now t.me/example",
      timestamp: now,
    },
    expected: {
      classification: "PROMO",
      parsed: false,
    },
  },
  {
    name: "media only",
    rawMessage: {
      channel: "fixture-media",
      messageId: 7,
      text: "",
      hasMedia: true,
      mediaType: "MessageMediaPhoto",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "old signal expires",
    rawMessage: {
      channel: "fixture-old",
      messageId: 8,
      text: "SELL GBP/USD 1.2700 TP 1.2650 SL 1.2740",
      timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GBPUSD",
      action: "SELL",
      signalStatus: "EXPIRED",
      signalState: "ACTIVE",
      freshnessScore: "STALE",
    },
  },
  {
    name: "spaced tp index and sl at marker",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 9,
      text: "XAUUSD SELL 4565\nTP 1 4560\nSL @ 4590",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4565,
      entryRange: [4565],
      targets: [4560],
      stopLoss: 4590,
    },
  },
  {
    name: "hyphenated tp indexes do not become targets",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 12,
      text: "Gold sell now at 4569 - 4579\nSL - 4585\nTP 1 - 4559\nTP 2 - 4549\nTP 3 - 4539",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4569,
      entryRange: [4569, 4579],
      targets: [4559, 4549, 4539],
      stopLoss: 4585,
    },
  },
  {
    name: "single tp price does not split into suffix target",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 13,
      text: "BUY XAUUSD 3345\nTP 3365\nSL 3330",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 3345,
      targets: [3365],
      stopLoss: 3330,
    },
  },
  {
    name: "plural take profits and compact stoploss",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 14,
      text: "Gold Buy Now @ 4510-4515\n\nStoploss: 4495\nTake profits: 4520 / 4522 / 4524",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4510,
      entryRange: [4510, 4515],
      targets: [4520, 4522, 4524],
      stopLoss: 4495,
    },
  },
  {
    name: "hashtag range open target vip stop",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 10,
      text: "#BUY #XAUUSD @4513 - 4510\nSL : VIP\nTP3 : OPEN+",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4513,
      entryRange: [4510, 4513],
      targets: ["OPEN"],
      stopLoss: null,
      hiddenStopLoss: true,
    },
  },
  {
    name: "pip targets stay separate from price targets",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 11,
      text: "Gold buy now @4556\nTP : 50Pips / 100Pips\nSL : VIP",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4556,
      entryRange: [4556],
      targets: [],
      pipTargets: [50, 100],
      stopLoss: null,
      hiddenStopLoss: true,
    },
  },
  {
    name: "top trading style audnzd hashtag labeled fields",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 18,
      text: "AUD-NZD Free Signal!\n\nSell!!\n\n#AUDNZD\n\nStop Loss: 1.2139\nTake Profit: 1.2084\nEntry: 1.2117",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "top trading style eurusd buy bang entry price",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 19,
      text: "EUR-USD Free Signal!\n\nBuy!\n\n#EURUSD\n\nTime Frame: H1\nEntry Price: 1.0842\nTarget: 1.0890\nSL: 1.0810\nJoin VIP: t.me/example",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.0842,
      targets: [1.089],
      stopLoss: 1.081,
    },
  },
  {
    name: "top trading style gbpjpy sell entry at target label",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 20,
      text: "GBP-JPY FREE SIGNAL\n\nSell\n\n#GBPJPY\n\nEntry @ 190.42\nTarget: 189.80\nStop Loss: 190.95\n✅ Free setup",
      timestamp: now,
    },
    expected: {
      classification: "MARKET_ANALYSIS",
      parsed: false,
    },
  },
  {
    name: "top trading style xauusd buy double bang tp sl",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 21,
      text: "XAU-USD Free Signal!\n\nBuy!!\n\n#XAUUSD\n\nEntry: 2345.50\nTP: 2352.00\nSL: 2339.80\n🚀",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2345.5,
      targets: [2352],
      stopLoss: 2339.8,
    },
  },
  {
    name: "entry point extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 101,
      text: "BUY EURUSD\nEntry Point - 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "entry price extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 102,
      text: "BUY EURUSD\nEntry Price: 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "entry plain extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 103,
      text: "BUY EURUSD\nEntry: 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "comma numbers entry tp sl test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 104,
      text: "BUY XAUUSD\nEntry: 6,428.3\nTP: 6,802.2\nSL: 4,233",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 6428.3,
      targets: [6802.2],
      stopLoss: 4233,
    },
  },
  {
    name: "comma numbers entry range test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 105,
      text: "BUY GER40\nEntry: 18,850 - 18,900\nTP: 19,000\nSL: 18,700",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GER40",
      action: "BUY",
      entry: 18850,
      entryRange: [18850, 18900],
      targets: [19000],
      stopLoss: 18700,
    },
  },
  {
    name: "entry level and target level parsing with commas",
    rawMessage: {
      channel: "fixture-test",
      messageId: 106,
      text: "GOLD Trade Direction: short\nEntry Level: 1,670.23\nTarget Level: 1,632.13\nStop Loss: 1,695.58",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 1670.23,
      targets: [1632.13],
      stopLoss: 1695.58,
    },
  },
  {
    name: "generalized variant 1",
    rawMessage: {
      channel: "fixture-test",
      messageId: 107,
      text: "#XAUUSD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 2",
    rawMessage: {
      channel: "fixture-test",
      messageId: 108,
      text: "#XAUUSD | BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 3",
    rawMessage: {
      channel: "fixture-test",
      messageId: 109,
      text: "XAUUSD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 4",
    rawMessage: {
      channel: "fixture-test",
      messageId: 110,
      text: "XAUUSD | BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 5",
    rawMessage: {
      channel: "fixture-test",
      messageId: 111,
      text: "BUY XAUUSD 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 6",
    rawMessage: {
      channel: "fixture-test",
      messageId: 112,
      text: "SELL XAUUSD 4304.00\nTarget 1 : 4300.00\nTarget 2 : 4296.00\nStoploss : 4308.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4304,
      targets: [4300, 4296],
      stopLoss: 4308,
    },
  },
  {
    name: "generalized variant 7",
    rawMessage: {
      channel: "fixture-test",
      messageId: 113,
      text: "GOLD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 8",
    rawMessage: {
      channel: "fixture-test",
      messageId: 114,
      text: "GOLD SELL 4304.00\nTarget 1 : 4300.00\nTarget 2 : 4296.00\nStoploss : 4308.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4304,
      targets: [4300, 4296],
      stopLoss: 4308,
    },
  },
  {
    name: "generalized variant 9",
    rawMessage: {
      channel: "fixture-test",
      messageId: 115,
      text: "XAU/USD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 10",
    rawMessage: {
      channel: "fixture-test",
      messageId: 116,
      text: "EUR/USD SELL 1.1556\nTarget 1 : 1.1500\nStoploss : 1.1600",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "SELL",
      entry: 1.1556,
      targets: [1.15],
      stopLoss: 1.16,
    },
  },
  {
    name: "generalized variant 11",
    rawMessage: {
      channel: "fixture-test",
      messageId: 117,
      text: "ETHUSD SELL 1670.23\nTarget 1 : 1650.00\nStoploss : 1700.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "ETHUSD",
      action: "SELL",
      entry: 1670.23,
      targets: [1650],
      stopLoss: 1700,
    },
  },
  {
    name: "generalized variant 12",
    rawMessage: {
      channel: "fixture-test",
      messageId: 118,
      text: "BTCUSD BUY 105000\nTarget 1 : 110000\nStoploss : 100000",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "BTCUSD",
      action: "BUY",
      entry: 105000,
      targets: [110000],
      stopLoss: 100000,
    },
  },
  {
    name: "precision buy from range format",
    rawMessage: {
      channel: "fixture-test",
      messageId: 119,
      text: "XAUUSD BUY FROM 4290 4287\n\nTP 4296\nTP 4303\nTP 4310\nTP 4320\n\nSL 4284",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4290,
      entryRange: [4287, 4290],
      targets: [4296, 4303, 4310, 4320],
      stopLoss: 4284,
    },
  },
  {
    name: "AnabelSignals gold bullish pivot level",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 101,
      text: "GOLD\nBias Bullish\npivot level: 2320.50\nGoal 1: 2335.00\nMy Stop Loss: 2310.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2320.50,
      targets: [2335.00],
      stopLoss: 2310.00,
    },
  },
  {
    name: "AnabelSignals silver bearish price coiling",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 102,
      text: "SILVER\nBias Bearish\nprice is coiling around 29.50\nGoal: 28.10\nSafe Stop Loss: 30.20",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAGUSD",
      action: "SELL",
      entry: 29.50,
      targets: [28.10],
      stopLoss: 30.20,
    },
  },
  {
    name: "AnabelSignals gold bullish approaching",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 103,
      text: "GOLD\nBias Bullish\nasset is approaching 2350.00\nGoal 1 2365\nRecommended Stop Loss 2340",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2350.00,
      targets: [2365],
      stopLoss: 2340,
    },
  },
  {
    name: "AnabelSignals gold bullish key and psychological level",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 104,
      text: "GOLD\nBias Bullish\nkey level: 2320.50\npsychological level 2318.00\nGoal 1: 2335.00\nMy Stop Loss: 2310.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2320.50,
      targets: [2335.00],
      stopLoss: 2310.00,
    },
  },
  {
    name: "Gold Anabel signals with hyphenated action",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 105,
      text: "GOLD SPOT\nBias - Bullish\npivot point 2320.00\nGoal 2340.00\nMy Stop Loss 2300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2320.00,
      targets: [2340.00],
      stopLoss: 2300.00,
    },
  },
  {
    name: "Silver Anabel signals with alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 106,
      text: "SILVER SPOT\nBias - Bearish\nkey level 30.50\nGoal 29.80\nSafe Stop Loss 31.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAGUSD",
      action: "SELL",
      entry: 30.50,
      targets: [29.80],
      stopLoss: 31.00,
    },
  },
  {
    name: "EURUSD Anabel signals hashtag and lowercase",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 107,
      text: "#EURUSD\nBias - Bullish\npsychological level 1.0850\nGoal 1.0920\nRecommended Stop Loss 1.0800",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.0850,
      targets: [1.0920],
      stopLoss: 1.0800,
    },
  },
  {
    name: "GBPJPY Anabel signals slash",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 108,
      text: "GBP/JPY\nBias - Bearish\nmarket is trading on 200.50\nGoal 199.00\nMy Stop Loss 201.50",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "AUDJPY Anabel signals slash lowercase",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 109,
      text: "aud/jpy\nBias - Bullish\nprice is coiling around 98.20\nGoal 99.50\nSafe Stop Loss 97.50",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "US30 Wall Street index alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 110,
      text: "WALL STREET\nBias - Bearish\ninstrument tests 39000\nGoal 38500\nRecommended Stop Loss 39300",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "US30",
      action: "SELL",
      entry: 39000,
      targets: [38500],
      stopLoss: 39300,
    },
  },
  {
    name: "US100 Nasdaq index alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 111,
      text: "NASDAQ\nBias - Bullish\nasset is approaching 18500\nGoal 19000\nMy Stop Loss 18200",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "US100",
      action: "BUY",
      entry: 18500,
      targets: [19000],
      stopLoss: 18200,
    },
  },
  {
    name: "QQQ ETF unknown alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 112,
      text: "QQQ\nBias - Bullish\npivot level 450.00\nGoal 460.00\nSafe Stop Loss 445.00",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "NATGAS Commodity alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 113,
      text: "NATURAL GAS\nBias - Bearish\nkey level 2.50\nGoal 2.20\nMy Stop Loss 2.70",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "NATGAS",
      action: "SELL",
      entry: 2.50,
      targets: [2.20],
      stopLoss: 2.70,
    },
  },
  {
    name: "TESLA Stock alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 114,
      text: "TESLA\nBias - Bullish\npsychological level 180.00\nGoal 195.00\nRecommended Stop Loss 170.00",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "APPLE Stock alias",
    rawMessage: {
      channel: "anabelsignals",
      messageId: 115,
      text: "APPLE\nBias - Bearish\nmarket is trading on 210.00\nGoal 200.00\nSafe Stop Loss 218.00",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "double slash entry range buy case",
    rawMessage: {
      channel: "fixture-test",
      messageId: 120,
      text: "XAUUSD BUY 4335//4330\nTP 4350\nSL 4320",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4335,
      entryRange: [4330, 4335],
      targets: [4350],
      stopLoss: 4320,
    },
  },
  {
    name: "double slash entry range sell case",
    rawMessage: {
      channel: "fixture-test",
      messageId: 121,
      text: "XAUUSD SELL 4351//4354\nTP 4330\nSL 4370",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4351,
      entryRange: [4351, 4354],
      targets: [4330],
      stopLoss: 4370,
    },
  },
  {
    name: "double slash entry range xauusd buy case",
    rawMessage: {
      channel: "fixture-test",
      messageId: 122,
      text: "XAUUSD BUY 3340//3335\nTP 3360\nSL 3320",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 3340,
      entryRange: [3335, 3340],
      targets: [3360],
      stopLoss: 3320,
    },
  },
  {
    name: "arixanderxx7 default pair mapping",
    rawMessage: {
      channel: "arixanderxx7",
      messageId: 1001,
      text: "BUY 4335-4330\nSL 4320\nTP 4350\nTP 4360\nTP 4370",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4335,
      entryRange: [4330, 4335],
      targets: [4350, 4360, 4370],
      stopLoss: 4320,
    },
  },
  {
    name: "normal channel no default pair mapping",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1002,
      text: "BUY 4335-4330\nSL 4320\nTP 4350\nTP 4360\nTP 4370",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "abbreviated entry range gold standard 1",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1003,
      text: "XAUUSD SELL\nEntry: 4325-27\nTP 4350\nSL 4300",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4325,
      entryRange: [4325, 4327],
      targets: [4350],
      stopLoss: 4300,
    },
  },
  {
    name: "abbreviated entry range gold standard 2",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1004,
      text: "XAUUSD BUY\nEntry: 4321-22\nTP 4350\nSL 4300",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4321,
      entryRange: [4321, 4322],
      targets: [4350],
      stopLoss: 4300,
    },
  },
  {
    name: "abbreviated entry range gold standard 3",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1005,
      text: "XAUUSD BUY\nEntry: 4335-37\nTP 4350\nSL 4300",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4335,
      entryRange: [4335, 4337],
      targets: [4350],
      stopLoss: 4300,
    },
  },
  {
    name: "abbreviated entry range gold standard 4",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1006,
      text: "XAUUSD SELL\nEntry: 4330-28\nTP 4310\nSL 4350",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4330,
      entryRange: [4328, 4330],
      targets: [4310],
      stopLoss: 4350,
    },
  },
  {
    name: "abbreviated entry range gold upward rollover 4399-01",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1007,
      text: "XAUUSD BUY\nEntry: 4399-01\nTP 4420\nSL 4380",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4399,
      entryRange: [4399, 4401],
      targets: [4420],
      stopLoss: 4380,
    },
  },
  {
    name: "abbreviated entry range gold upward rollover 4298-02",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1008,
      text: "XAUUSD BUY\nEntry: 4298-02\nTP 4320\nSL 4280",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4298,
      entryRange: [4298, 4302],
      targets: [4320],
      stopLoss: 4280,
    },
  },
  {
    name: "abbreviated entry range gold decimals 2715.5-17.5",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1009,
      text: "XAUUSD BUY\nEntry: 2715.5-17.5\nTP 2730\nSL 2700",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2715.5,
      entryRange: [2715.5, 2717.5],
      targets: [2730],
      stopLoss: 2700,
    },
  },
  {
    name: "abbreviated entry range forex untreated 1.0820-25",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1010,
      text: "EURUSD BUY\nEntry: 1.0820-25\nTP 1.0880\nSL 1.0780",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.082,
      entryRange: [1.082, 25],
      targets: [1.088],
      stopLoss: 1.078,
    },
  },
  {
    name: "target noise filter Case 1 - promo deposit and url",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1011,
      text: "XAUUSD BUY\nEntry: 4280\nTP 4290\nSL 4270\n\n⭐ Deposit $300\nhttps://puvip.co/VvQz2e",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4280,
      targets: [4290],
      stopLoss: 4270,
    },
  },
  {
    name: "target noise filter Case 2 - join VIP telegram url",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1012,
      text: "XAUUSD BUY\nEntry: 4300\nTP 4315\nSL 4290\n\nJoin VIP:\nhttps://t.me/example",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4300,
      targets: [4315],
      stopLoss: 4290,
    },
  },
  {
    name: "target noise filter Case 3 - multiple targets no noise",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1013,
      text: "XAUUSD BUY\nEntry: 4300\nTP 4320\nTP 4310\nTP 4290\nSL 4280",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4300,
      targets: [4320, 4310, 4290],
      stopLoss: 4280,
    },
  },
  {
    name: "target noise filter Case 4 - promo deposit and contact number",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1014,
      text: "XAUUSD BUY\nEntry: 4280\nTP 4290\nSL 4270\n\nDeposit $500\nContact +123456789",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4280,
      targets: [4290],
      stopLoss: 4270,
    },
  },
  {
    name: "target noise filter Case 5 - indexed TP targets",
    rawMessage: {
      channel: "fixture-test",
      messageId: 1015,
      text: "XAUUSD BUY\nEntry: 4300\nTP1 4320\nTP2 4310\nTP3 4290\nSL 4280",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4300,
      targets: [4320, 4310, 4290],
      stopLoss: 4280,
    },
  },
  {
    name: "Case 1: DXY signal with goldvip in footer",
    rawMessage: {
      channel: "gold_signals",
      messageId: 3663,
      text: "📊DXY: Market Is Looking Up! Buy!\n\n🆓SIGNAL DETAILS \n——————\nENTER: #DXY  long trade  \nCURRENT PRICE: 99.622\nSTOP LOSS: 99.574\nTAKE PROFIT: 99.693\n——————\n✈️ CONTACT TO JOIN GOLD SIGNALS VIP👉🏻 @goldvip_contact",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "DXY",
      action: "BUY",
      entry: 99.622,
      targets: [99.693],
      stopLoss: 99.574,
    },
  },
  {
    name: "Case 2: BTCUSD signal with gold trader vip in footer",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 2002,
      text: "BTCUSD BUY 98000\nTP 100000\nSL 96000\n\nJoin our gold trader vip group today!",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "BTCUSD",
      action: "BUY",
      entry: 98000,
      targets: [100000],
      stopLoss: 96000,
    },
  },
  {
    name: "Case 3: NAS100 signal with gold in footer",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 2003,
      text: "NAS100 BUY 20000\nTP 20200\nSL 19900\n\nGet gold vip access now.",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "US100",
      action: "BUY",
      entry: 20000,
      targets: [20200],
      stopLoss: 19900,
    },
  },
  {
    name: "Case 4: XAUUSD signal with btcvip in footer",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 2004,
      text: "XAUUSD SELL 2700\nTP 2650\nSL 2720\n\nJoin our btcvip community at t.me/btcvip",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 2700,
      targets: [2650],
      stopLoss: 2720,
    },
  },
  {
    name: "Case 5: No pair present and goldvip in footer",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 2005,
      text: "BUY 1.0900\nTP 1.0950\nSL 1.0850\n\n@gold_signals",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
];
