const now = new Date().toISOString();

export const parserFixtures = [
  {
    name: "clean multiline gold signal",
    rawMessage: {
      channel: "fixture-clean",
      messageId: 1,
      text: "BUY GOLD ENTRY 3345\nTP1 3350\nTP2 3360\nSL 3335",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 3345,
      targets: [3350, 3360],
      stopLoss: 3335,
      signalStatus: "ACTIVE",
      signalState: "ACTIVE",
      freshnessScore: "VERY_FRESH",
    },
  },
  {
    name: "emoji and symbol noisy partial",
    rawMessage: {
      channel: "fixture-noisy",
      messageId: 2,
      text: "🚀🚀 BUY GOLD NOW 🔥🔥",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: null,
      signalStatus: "ACTIVE",
    },
  },
  {
    name: "unordered fields",
    rawMessage: {
      channel: "fixture-unordered",
      messageId: 3,
      text: "TP1 1.0920\nSL 1.0840\nEUR/USD buy @ 1.0880\nTP2 1.0960",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.088,
      targets: [1.092, 1.096],
      stopLoss: 1.084,
    },
  },
  {
    name: "dynamic crypto quoted pair",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 15,
      text: "BUY SOLUSDT @ 142.50\nTP1 146\nSL 139",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "SOLUSDT",
      action: "BUY",
      entry: 142.5,
      targets: [146],
      stopLoss: 139,
    },
  },
  {
    name: "dynamic index pair",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 16,
      text: "GER40 SELL 18850\nTP 18790\nSL 18910",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GER40",
      action: "SELL",
      entry: 18850,
      targets: [18790],
      stopLoss: 18910,
    },
  },
  {
    name: "silver alias normalizes to xagusd",
    rawMessage: {
      channel: "fixture-dynamic-pair",
      messageId: 17,
      text: "SILVER BUY @ 31.25\nTP1 31.80\nSL 30.90",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAGUSD",
      action: "BUY",
      entry: 31.25,
      targets: [31.8],
      stopLoss: 30.9,
    },
  },
  {
    name: "update breakeven",
    rawMessage: {
      channel: "fixture-update",
      messageId: 4,
      text: "Move SL to breakeven",
      timestamp: now,
    },
    expected: {
      classification: "UPDATE_SIGNAL",
      managementAction: "MOVE_SL_BREAKEVEN",
      signalStatus: "ACTIVE",
      signalState: "ACTIVE",
    },
  },
  {
    name: "result target hit",
    rawMessage: {
      channel: "fixture-result",
      messageId: 5,
      text: "TP1 HIT ✅",
      timestamp: now,
    },
    expected: {
      classification: "RESULT_SIGNAL",
      resultActionType: "TARGET_HIT",
      signalStatus: "PARTIAL",
      signalState: "PARTIAL",
    },
  },
  {
    name: "promo spam",
    rawMessage: {
      channel: "fixture-promo",
      messageId: 6,
      text: "Join VIP now t.me/example",
      timestamp: now,
    },
    expected: {
      classification: "PROMO",
      parsed: false,
    },
  },
  {
    name: "media only",
    rawMessage: {
      channel: "fixture-media",
      messageId: 7,
      text: "",
      hasMedia: true,
      mediaType: "MessageMediaPhoto",
      timestamp: now,
    },
    expected: {
      classification: "NOISE",
      parsed: false,
    },
  },
  {
    name: "old signal expires",
    rawMessage: {
      channel: "fixture-old",
      messageId: 8,
      text: "SELL GBP/USD 1.2700 TP 1.2650 SL 1.2740",
      timestamp: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GBPUSD",
      action: "SELL",
      signalStatus: "EXPIRED",
      signalState: "ACTIVE",
      freshnessScore: "STALE",
    },
  },
  {
    name: "spaced tp index and sl at marker",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 9,
      text: "XAUUSD SELL 4565\nTP 1 4560\nSL @ 4590",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4565,
      entryRange: [4565],
      targets: [4560],
      stopLoss: 4590,
    },
  },
  {
    name: "hyphenated tp indexes do not become targets",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 12,
      text: "Gold sell now at 4569 - 4579\nSL - 4585\nTP 1 - 4559\nTP 2 - 4549\nTP 3 - 4539",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4569,
      entryRange: [4569, 4579],
      targets: [4559, 4549, 4539],
      stopLoss: 4585,
    },
  },
  {
    name: "single tp price does not split into suffix target",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 13,
      text: "BUY XAUUSD 3345\nTP 3365\nSL 3330",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 3345,
      targets: [3365],
      stopLoss: 3330,
    },
  },
  {
    name: "plural take profits and compact stoploss",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 14,
      text: "Gold Buy Now @ 4510-4515\n\nStoploss: 4495\nTake profits: 4520 / 4522 / 4524",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4510,
      entryRange: [4510, 4515],
      targets: [4520, 4522, 4524],
      stopLoss: 4495,
    },
  },
  {
    name: "hashtag range open target vip stop",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 10,
      text: "#BUY #XAUUSD @4513 - 4510\nSL : VIP\nTP3 : OPEN+",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4513,
      entryRange: [4510, 4513],
      targets: ["OPEN"],
      stopLoss: null,
      hiddenStopLoss: true,
    },
  },
  {
    name: "pip targets stay separate from price targets",
    rawMessage: {
      channel: "fixture-real-telegram",
      messageId: 11,
      text: "Gold buy now @4556\nTP : 50Pips / 100Pips\nSL : VIP",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4556,
      entryRange: [4556],
      targets: [],
      pipTargets: [50, 100],
      stopLoss: null,
      hiddenStopLoss: true,
    },
  },
  {
    name: "top trading style audnzd hashtag labeled fields",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 18,
      text: "AUD-NZD Free Signal!\n\nSell!!\n\n#AUDNZD\n\nStop Loss: 1.2139\nTake Profit: 1.2084\nEntry: 1.2117",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "AUDNZD",
      action: "SELL",
      entry: 1.2117,
      targets: [1.2084],
      stopLoss: 1.2139,
    },
  },
  {
    name: "top trading style eurusd buy bang entry price",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 19,
      text: "EUR-USD Free Signal!\n\nBuy!\n\n#EURUSD\n\nTime Frame: H1\nEntry Price: 1.0842\nTarget: 1.0890\nSL: 1.0810\nJoin VIP: t.me/example",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.0842,
      targets: [1.089],
      stopLoss: 1.081,
    },
  },
  {
    name: "top trading style gbpjpy sell entry at target label",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 20,
      text: "GBP-JPY FREE SIGNAL\n\nSell\n\n#GBPJPY\n\nEntry @ 190.42\nTarget: 189.80\nStop Loss: 190.95\n✅ Free setup",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GBPJPY",
      action: "SELL",
      entry: 190.42,
      targets: [189.8],
      stopLoss: 190.95,
    },
  },
  {
    name: "top trading style xauusd buy double bang tp sl",
    rawMessage: {
      channel: "fixture-top-trading-style",
      messageId: 21,
      text: "XAU-USD Free Signal!\n\nBuy!!\n\n#XAUUSD\n\nEntry: 2345.50\nTP: 2352.00\nSL: 2339.80\n🚀",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 2345.5,
      targets: [2352],
      stopLoss: 2339.8,
    },
  },
  {
    name: "entry point extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 101,
      text: "BUY EURUSD\nEntry Point - 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "entry price extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 102,
      text: "BUY EURUSD\nEntry Price: 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "entry plain extraction test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 103,
      text: "BUY EURUSD\nEntry: 1.1556\nTP 1.1600\nSL 1.1500",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "BUY",
      entry: 1.1556,
      targets: [1.16],
      stopLoss: 1.15,
    },
  },
  {
    name: "comma numbers entry tp sl test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 104,
      text: "BUY XAUUSD\nEntry: 6,428.3\nTP: 6,802.2\nSL: 4,233",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 6428.3,
      targets: [6802.2],
      stopLoss: 4233,
    },
  },
  {
    name: "comma numbers entry range test",
    rawMessage: {
      channel: "fixture-test",
      messageId: 105,
      text: "BUY GER40\nEntry: 18,850 - 18,900\nTP: 19,000\nSL: 18,700",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "GER40",
      action: "BUY",
      entry: 18850,
      entryRange: [18850, 18900],
      targets: [19000],
      stopLoss: 18700,
    },
  },
  {
    name: "entry level and target level parsing with commas",
    rawMessage: {
      channel: "fixture-test",
      messageId: 106,
      text: "GOLD Trade Direction: short\nEntry Level: 1,670.23\nTarget Level: 1,632.13\nStop Loss: 1,695.58",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 1670.23,
      targets: [1632.13],
      stopLoss: 1695.58,
    },
  },
  {
    name: "generalized variant 1",
    rawMessage: {
      channel: "fixture-test",
      messageId: 107,
      text: "#XAUUSD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 2",
    rawMessage: {
      channel: "fixture-test",
      messageId: 108,
      text: "#XAUUSD | BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 3",
    rawMessage: {
      channel: "fixture-test",
      messageId: 109,
      text: "XAUUSD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 4",
    rawMessage: {
      channel: "fixture-test",
      messageId: 110,
      text: "XAUUSD | BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 5",
    rawMessage: {
      channel: "fixture-test",
      messageId: 111,
      text: "BUY XAUUSD 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 6",
    rawMessage: {
      channel: "fixture-test",
      messageId: 112,
      text: "SELL XAUUSD 4304.00\nTarget 1 : 4300.00\nTarget 2 : 4296.00\nStoploss : 4308.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4304,
      targets: [4300, 4296],
      stopLoss: 4308,
    },
  },
  {
    name: "generalized variant 7",
    rawMessage: {
      channel: "fixture-test",
      messageId: 113,
      text: "GOLD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 8",
    rawMessage: {
      channel: "fixture-test",
      messageId: 114,
      text: "GOLD SELL 4304.00\nTarget 1 : 4300.00\nTarget 2 : 4296.00\nStoploss : 4308.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "SELL",
      entry: 4304,
      targets: [4300, 4296],
      stopLoss: 4308,
    },
  },
  {
    name: "generalized variant 9",
    rawMessage: {
      channel: "fixture-test",
      messageId: 115,
      text: "XAU/USD BUY 4304.00\nTarget 1 : 4308.00\nTarget 2 : 4312.00\nStoploss : 4300.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4304,
      targets: [4308, 4312],
      stopLoss: 4300,
    },
  },
  {
    name: "generalized variant 10",
    rawMessage: {
      channel: "fixture-test",
      messageId: 116,
      text: "EUR/USD SELL 1.1556\nTarget 1 : 1.1500\nStoploss : 1.1600",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "EURUSD",
      action: "SELL",
      entry: 1.1556,
      targets: [1.15],
      stopLoss: 1.16,
    },
  },
  {
    name: "generalized variant 11",
    rawMessage: {
      channel: "fixture-test",
      messageId: 117,
      text: "ETHUSD SELL 1670.23\nTarget 1 : 1650.00\nStoploss : 1700.00",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "ETHUSD",
      action: "SELL",
      entry: 1670.23,
      targets: [1650],
      stopLoss: 1700,
    },
  },
  {
    name: "generalized variant 12",
    rawMessage: {
      channel: "fixture-test",
      messageId: 118,
      text: "BTCUSD BUY 105000\nTarget 1 : 110000\nStoploss : 100000",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "BTCUSD",
      action: "BUY",
      entry: 105000,
      targets: [110000],
      stopLoss: 100000,
    },
  },
  {
    name: "precision buy from range format",
    rawMessage: {
      channel: "fixture-test",
      messageId: 119,
      text: "XAUUSD BUY FROM 4290 4287\n\nTP 4296\nTP 4303\nTP 4310\nTP 4320\n\nSL 4284",
      timestamp: now,
    },
    expected: {
      classification: "NEW_SIGNAL",
      pair: "XAUUSD",
      action: "BUY",
      entry: 4290,
      entryRange: [4287, 4290],
      targets: [4296, 4303, 4310, 4320],
      stopLoss: 4284,
    },
  },
];
